name: Bump Semantic Version

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Bump Version
        id: bump_semver
        run: |
          version=$(cat version.txt)
          IFS='.' read -r -a parts <<< "$version"
          patch=$((parts[2] + 1))
          new_version="${parts[0]}.${parts[1]}.$patch"
          echo $new_version > version.txt
          echo "new_version=$new_version" >> $GITHUB_ENV

      - name: Commit Version Bump
        env: 
          GITHUB_TOKEN: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add version.txt
          git commit -m "Bump version to ${{ env.new_version }}"
          git remote set-url origin https://github-actions:${{ secrets.ACTIONS_GITHUB_TOKEN }}@github.com/kulik95/react-hello-world.git
          git push origin main
