name: Package and Push Helm Chart

on:
  push:
    branches:
      - main

jobs:
  package-helm-chart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Package Helm Chart
        run: helm package ./charts/react-hello-world -d ./charts
        
      - uses: actions/checkout@v3
        with:
          repository: kulik95/helm-charts
          ref: 'main'
          token:  ${{ secrets.ACTIONS_GITHUB_TOKEN }}
      - name: Push to Helm Charts Repo
        run: |
          pwd
          git clone https://github.com/kulik95/helm-charts.git
          mv ./charts/react-hello-world-*.tgz helm-charts/
          cd helm-charts
          helm repo index .
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Add react-hello-world chart"
          git push origin main
